function cg = BPEAsymptotic(x, t, k, a1, a2, a12, b)

  cg = 0.2e1 * a12 * (k ^ 2) * ...
      (a1 * a2 ^ 2 * exp(-(k * x) - sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t - b) + ...
       0.4e1 * a1 * a12 * a2 +...
       a1 * a12 ^ 2 * exp(sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t + (k * x) + b) +...
       a2 * a1 ^ 2 * exp((k * x) - sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t - b) +...
       a2 * a12 ^ 2 * exp(-(k * x) + sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t + b)) ./ ...
       (a1 ^ 2 * exp((k * x) - sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t - b) +...
       0.2e1 * a1 * a12 + a12 ^ 2 * exp(-(k * x) + sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t + b)) ./ ...
       (a2 ^ 2 * exp(-(k * x) - sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t - b) +...
       0.2e1 * a12 * a2 + a12 ^ 2 * exp(sqrt(-(k ^ 2 * (-1 + k ^ 2))) * t + (k * x) + b));

end